
package com.viettel.passport;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import org.springframework.beans.factory.annotation.Value;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */



/*@WebServiceClient(name = "passportWSService", targetNamespace = "http://passport.viettel.com/", wsdlLocation = "http://10.58.71.44:8180/passportv3/passportWS?wsdl")*/
@WebServiceClient(name = "passportWSService", targetNamespace = "http://passport.viettel.com/", wsdlLocation = "http://10.60.7.126:8660/passportv3/passportWS?wsdl")


public class PassportWSService
    extends Service
{

	@Value("${SSO_URL}")
	private static String SSO_URL;

    private final static URL PASSPORTWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException PASSPORTWSSERVICE_EXCEPTION;
    private final static QName PASSPORTWSSERVICE_QNAME = new QName("http://passport.viettel.com/", "passportWSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
           /* url = new URL("http://10.58.71.44:8180/passportv3/passportWS?wsdl");*/
            url = new URL("http://10.60.7.126:8660/passportv3/passportWS?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PASSPORTWSSERVICE_WSDL_LOCATION = url;
        PASSPORTWSSERVICE_EXCEPTION = e;
    }

    public PassportWSService() {
        super(__getWsdlLocation(), PASSPORTWSSERVICE_QNAME);
    }

    public PassportWSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PASSPORTWSSERVICE_QNAME, features);
    }

    public PassportWSService(URL wsdlLocation) {
        super(wsdlLocation, PASSPORTWSSERVICE_QNAME);
    }

    public PassportWSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PASSPORTWSSERVICE_QNAME, features);
    }

    public PassportWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PassportWSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PassportWS
     */
    @WebEndpoint(name = "passportWSPort")
    public PassportWS getPassportWSPort() {
        return super.getPort(new QName("http://passport.viettel.com/", "passportWSPort"), PassportWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PassportWS
     */
    @WebEndpoint(name = "passportWSPort")
    public PassportWS getPassportWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://passport.viettel.com/", "passportWSPort"), PassportWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PASSPORTWSSERVICE_EXCEPTION!= null) {
            throw PASSPORTWSSERVICE_EXCEPTION;
        }
        return PASSPORTWSSERVICE_WSDL_LOCATION;
    }

}
